version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lawless
      - POSTGRES_USER=lawless
      - POSTGRES_PASSWORD=lawless

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=lawless
      - POSTGRES_USER=lawless
      - POSTGRES_PASSWORD=lawless
    depends_on:
      - db

  cron:
    image: nextcloud
    restart: always
    volumes:
      - lawless:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db:
  lawless:
